version: ''
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: fleet_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "2547:3306" 
    volumes:
      - db_data:/var/lib/mysql
      - ./Schema.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
  phpmyadmin:
      image: phpmyadmin:latest
      restart: always
      ports:
        - "9090:80" # เข้าผ่าน http://localhost:9090
      environment:
        - PMA_HOST=db
        - MYSQL_ROOT_PASSWORD=password
      depends_on:
        db:
          condition: service_healthy

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=fleet_db
      - JWT_SECRET=fleet_jwt_secret_2024_v2
      - JWT_REFRESH_SECRET=fleet_refresh_secret_2024_v2
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./frontend:/app/frontend
      - ./scripts:/app/scripts
      - ./backend/src:/app/src
      - ./backend/scripts:/app/scripts
    command: >
      sh -c "node scripts/seed.js && node src/index.js"
    restart: unless-stopped

volumes:
  db_data: